/**
 * PURE state for the human-in-the-loop ofício editing (SPEC §8).
 *
 * The Drafter generates `OficioGerado.markdown`; before export (Phase
 * 14) Stefany can edit it. Phase 13 ships only the controlled EDITABLE
 * textarea + this local state. Keeping `original` makes it trivial to:
 *  - detect whether it was edited (`foiEditado`) — diff signal for §11b;
 *  - revert to the generated text.
 *
 * No React here on purpose: the component only wires onChange→editarTexto.
 */

export type EdicaoOficio = {
  /** Current textarea text (controlled state). */
  texto: string;
  /** Markdown originally generated by the Drafter (for revert/diff). */
  original: string;
};

export function inicializarEdicao(markdownGerado: string): EdicaoOficio {
  return { texto: markdownGerado, original: markdownGerado };
}

export function editarTexto(e: EdicaoOficio, novo: string): EdicaoOficio {
  return { ...e, texto: novo };
}

export function reverter(e: EdicaoOficio): EdicaoOficio {
  return { ...e, texto: e.original };
}

/** Was there a human edit? (text differs from the generated one). */
export function foiEditado(e: EdicaoOficio): boolean {
  return e.texto !== e.original;
}
