import { describe, it, expect } from 'vitest';
import {
  inicializarEdicao,
  editarTexto,
  reverter,
  foiEditado,
} from './oficio-edicao.ts';

/**
 * Estado da edição human-in-the-loop do ofício (SPEC §8). Phase 13 só
 * entrega a textarea EDITÁVEL + estado local controlado; o export é
 * Phase 14. Testa: estado controlado (texto muda), detecção de
 * "foi editado" (sinal de diff p/ §11b futuro) e reverter ao gerado.
 */

describe('ofício editing — controlled textarea', () => {
  it('initializes with the markdown generated by the Drafter', () => {
    const e = inicializarEdicao('# Ofício\nCorpo gerado');
    expect(e.texto).toBe('# Ofício\nCorpo gerado');
    expect(e.original).toBe('# Ofício\nCorpo gerado');
    expect(foiEditado(e)).toBe(false);
  });

  it('editarTexto updates the text (controlled state)', () => {
    let e = inicializarEdicao('original');
    e = editarTexto(e, 'texto editado pela Stefany');
    expect(e.texto).toBe('texto editado pela Stefany');
    expect(e.original).toBe('original');
    expect(foiEditado(e)).toBe(true);
  });

  it('foiEditado is false if it returns to the original text', () => {
    let e = inicializarEdicao('abc');
    e = editarTexto(e, 'abc xyz');
    expect(foiEditado(e)).toBe(true);
    e = editarTexto(e, 'abc');
    expect(foiEditado(e)).toBe(false);
  });

  it('reverter restores the generated markdown', () => {
    let e = inicializarEdicao('gerado');
    e = editarTexto(e, 'rabiscado');
    e = reverter(e);
    expect(e.texto).toBe('gerado');
    expect(foiEditado(e)).toBe(false);
  });

  it('empty text is a valid editing state (controlled)', () => {
    let e = inicializarEdicao('algo');
    e = editarTexto(e, '');
    expect(e.texto).toBe('');
    expect(foiEditado(e)).toBe(true);
  });
});
