/**
 * Domain ports (hexagonal). Type-only: zero runtime dependency.
 * Concrete adapters (Gemini, Prisma, etc.) implement these interfaces;
 * the `application/` orchestrates them without knowing the technology.
 *
 * Pipeline sequence (SPEC §4):
 *   Preprocessor → Extractor → gate A → NormaVerifier? → RiskAnalyst
 *   → gate B → Drafter? → persists (AnalysisRepo) + Telemetry.
 */
import type {
  EditalExtraction,
  ExtractorOutput,
  FonteMeta,
} from './schema.ts';

export type { FonteMeta };

/** Preprocessor result: plain text + observed source metadata. */
export type TextoExtraido = {
  texto: string;
  fonte: FonteMeta;
};

/** Raw edital input (file received via upload). */
export type ArquivoEntrada = {
  nomeArquivo: string;
  bytes: Uint8Array;
  url: string | null;
};

/**
 * 1. Preprocessor — zip/gz/pdf → text (pdftotext -layout in the worker).
 * `fonte.ocr=true` when the extracted text comes back empty (signals the
 * need for downstream OCR).
 */
export interface PreprocessorPort {
  preprocessar(arquivo: ArquivoEntrada): Promise<TextoExtraido>;
}

/**
 * 2. Extractor — Gemini Flash, no tool. Produces `ExtractorOutput`
 * (schema v3 WITHOUT `pontosDeAtencao`). That field belongs to the Risk
 * Analyst (step 5, SPEC §4) — the Extractor does NOT produce it; the
 * `application/` reassembles the full `EditalExtraction` with
 * `pontosDeAtencao: []` before the Risk Analyst fills it. `revogada` flags
 * are PROVISIONAL (a guess); `statusVerificado` stays at the default
 * `nao-verificado` until the NormaVerifier.
 */
export interface ExtractorPort {
  extrair(texto: string, fonte: FonteMeta): Promise<ExtractorOutput>;
}

/**
 * 4. Norma Verifier (conditional, triggered by gate A) — baseline
 * (precedence, zero cost) → web grounding (tail) → cache. Returns the
 * extraction with `leisReferenciadas[].statusVerificado` and
 * `fonteVerificacao` filled in.
 */
export interface NormaVerifierPort {
  verificar(e: EditalExtraction): Promise<EditalExtraction>;
}

/**
 * 5. Risk Analyst — fills `pontosDeAtencao[]`, consuming the already
 * VERIFIED status of the laws (never the extractor's raw flag).
 */
export interface RiskAnalystPort {
  analisar(e: EditalExtraction): Promise<EditalExtraction>;
}

/** Validity status asserted by the Drafter, per cited law (SPEC §5 #2). */
export type AfirmacaoVigencia = 'nenhuma' | 'revogada' | 'vigente';

/** Structured Drafter decision per cited law (containment §5 #2). */
export type LeiNoOficio = {
  numero: string | null;
  ano: number | null;
  afirmacaoVigencia: AfirmacaoVigencia;
};

/** Ofício generated by the Drafter (conditional, triggered by gate B). */
export type OficioGerado = {
  tipo: 'esclarecimento' | 'impugnacao';
  markdown: string;
  leisCitadas: LeiNoOficio[];
};

/**
 * 7. Drafter (conditional) — decides `afirmacaoVigencia` per law and
 * generates the prose FROM that decision (order: decide→write). It only
 * asserts revocation if `statusVerificado=revogada`; otherwise it asks the
 * agency.
 *
 * Returns `null` when NOTHING justifies a manifestation (no incoherences,
 * ambiguous excerpts, or points of attention that recommend a
 * manifestation). The workflow (Phase 10) also applies gate B; the
 * Drafter, in turn, is defensive and returns `null` if the extraction
 * brings nothing to question.
 */
export interface DrafterPort {
  redigir(e: EditalExtraction): Promise<OficioGerado | null>;
}

/** Persisted analysis (extraction JSON + generated/exported ofício). */
export type AnaliseRegistro = {
  id: string;
  jobId: string;
  municipio: string;
  uf: string;
  extracao: EditalExtraction;
  oficioGerado: OficioGerado | null;
  /**
   * Ofício text EXACTLY as exported by Stefany (the editable textarea of
   * Phase 13). Persisted at the MOMENT of export (Phase 14) — the diff
   * `oficioGerado` × `oficioExportado` is the eval gold signal (§11b).
   * The ofício PDF is rendered from THIS text, never regenerated from the
   * original JSON/markdown (SPEC §9 — persist content, never the PDF).
   */
  oficioExportado: string | null;
  /** Timestamp of the ofício export (null until the 1st export). */
  oficioExportadoEm: Date | null;
};

/** Analysis repository (adapters/repo, the only one to touch Prisma). */
export interface AnalysisRepo {
  salvar(
    registro: Omit<AnaliseRegistro, 'id'>
  ): Promise<AnaliseRegistro>;
  buscarPorId(id: string): Promise<AnaliseRegistro | null>;
  /**
   * Fetches the analysis of a Job (1:1 in V0). `/api/status/:id` receives
   * the jobId; the UI never knows the Analysis id — only the Job's.
   */
  buscarPorJobId(jobId: string): Promise<AnaliseRegistro | null>;
  /**
   * Persists the edited ofício text at the MOMENT of export (Phase 14,
   * §9): writes `oficioExportado` + `oficioExportadoEm`. The PDF is then
   * rendered from the text NOW persisted — never regenerated from the
   * JSON. Returns the updated record.
   */
  registrarOficioExportado(
    id: string,
    texto: string
  ): Promise<AnaliseRegistro>;
  /**
   * Lists the most recent analyses (desc by `createdAt`) — internal
   * review surface (`/admin`, SPEC §11b: "without this the loop does not
   * close"). Sensible `limite` default; read-only.
   */
  listarRecentes(limite?: number): Promise<AnaliseRegistro[]>;
}

export type JobStatus = 'pending' | 'running' | 'done' | 'erro';

export type Job = {
  id: string;
  status: JobStatus;
  erro: string | null;
  inputRef: string;
  createdAt: Date;
};

/**
 * Job repository. `claimNext` performs the atomic claim
 * (FOR UPDATE SKIP LOCKED) — two workers never pick the same job.
 */
export interface JobRepo {
  criar(inputRef: string): Promise<Job>;
  claimNext(): Promise<Job | null>;
  marcarConcluido(id: string): Promise<void>;
  marcarErro(id: string, erro: string): Promise<void>;
  buscarPorId(id: string): Promise<Job | null>;
}

export type NormaStatus =
  | 'vigente'
  | 'revogada'
  | 'contestada'
  | 'inexistente'
  | 'nao-verificado';

export type NormaCacheEntry = {
  chave: string;
  status: NormaStatus;
  fonte: string;
  verificadoEm: Date;
};

/** Cache of verified norma status (reused across analyses). */
export interface NormaCache {
  obter(chave: string): Promise<NormaCacheEntry | null>;
  gravar(
    entry: Omit<NormaCacheEntry, 'verificadoEm'>
  ): Promise<void>;
}

/** A materialized telemetry event (read — /admin surface). */
export type EventoTelemetria = {
  analysisId: string;
  evento: string;
  payload: Record<string, unknown>;
  createdAt: Date;
};

/**
 * Telemetry — implicit events (export, re-upload, panels, latency) and the
 * per-call grounding cost logged individually (SPEC §11b). NON-blocking
 * write (via `application/telemetria.registrarSeguro`); the read
 * (`listarPorAnalises`) only feeds the internal review surface (`/admin`)
 * — read-only, outside the pipeline path.
 */
export interface TelemetryPort {
  registrar(
    analysisId: string,
    evento: string,
    payload: Record<string, unknown>
  ): Promise<void>;
  /**
   * Events of the given analyses (for `/admin`: feedback + diffs per
   * analysis). Returns only the events whose `analysisId` ∈ `ids`.
   */
  listarPorAnalises(ids: string[]): Promise<EventoTelemetria[]>;
}
